name: Build & Deploy App to AKS

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: myacrname
  IMAGE_NAME: sampleapp
  AKS_CLUSTER: aks-devops
  AKS_RG: rg-devops

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Azure login via OIDC
    - name: Azure Login (OIDC)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Unit Tests
    - name: Run Unit Tests
      run: |
        cd app
        docker build -t test-image .
        docker run test-image pytest tests/

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t acrprodassignmnet3.azurecr.io/$IMAGE_NAME:${{ github.sha }} app

    # Trivy Image Scan
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: acrprodassignmnet3.azurecr.io/$IMAGE_NAME:${{ github.sha }}
        severity: HIGH,CRITICAL
        exit-code: '1'

    # Login to ACR using OIDC
    - name: ACR Login
      run: az acr login --name acrprodassignmnet3

    # Push Image to ACR
    - name: Push Image
      run: |
        docker push acrprodassignmnet3.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    # Get AKS credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group $AKS_RG \
          --name $AKS_CLUSTER \
          --overwrite-existing

    # Deploy to AKS
    - name: Deploy to AKS
      run: |
        sed -i "s|IMAGE_TAG|${{ github.sha }}|g" app/k8s/deployment.yaml
        kubectl apply -f app/k8s/

    # Health Check
    - name: Wait for Pods
      run: |
        kubectl rollout status deployment/sampleapp --timeout=120s